drop table if exists USERINFO CASCADE;
create table USERINFO
(
 id bigint generated by default as identity,
 email varchar(255),password varchar(255),phone varchar(255),name varchar(255),title varchar(255),website varchar(255),
 primary key (id)
);